routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
Route::get('/','HomeController@index');
Route::get('about','HomeController@about');
Route::get('faq','HomeController@faq');
Route::get('contact','HomeController@contact');
Route::get('service','HomeController@service');
Route::get('chart','HomeController@chart');
Route::get('pricing','HomeController@pricing');
Route::get('technical-analysis','HomeController@technicalAnalysis');
Route::get('stock-chart','HomeController@stockChart');
Route::get('news','HomeController@news');
Route::get('explore','HomeController@explore');
Route::get('complain','HomeController@complain');
Route::get('refund-policy','HomeController@refundPolice');
Route::get('risk-discloser','HomeController@riskdiscloser');
Route::get('disclaimer','HomeController@disclaimer');
Route::get('terms_condition','HomeController@terms_condition');
Route::get('reviews','HomeController@reviews');
Route::get('risk-profile','HomeController@risk_profile');
Route::get('kyc','HomeController@kyc');
Route::get('kyc-individual','HomeController@kycIndividual');
Route::post('/kyc-Post-individual','KycController@Individual');
Route::post('/kyc-Post-Non-Individual','Kyc_Non_Individual_Controller@Non_Individual');
Route::get('kyc-non-individual','HomeController@kycNonIndividual');
Route::get('download_individual','KycController@getDownload');
Route::get('download_non_individual','Kyc_Non_Individual_Controller@getDownload');
Route::post('/upload_kyc_form','Upload_Kyc_Form_Controller@upload_kyc_form');
Route::get('risk-profile-form','HomeController@riskProfileForm');
Route::get('/blog','HomeController@blog');
Route::get('blog-detail/{id}','HomeController@blogDetail');
Route::get('news-detail/{id}','HomeController@newsDetail');
Route::get('service/{service}','HomeController@serviceList')->name('list.service');
Route::get('state/{id}','HomeController@stateId');
Route::get('city/{id}','HomeController@cityId');
Route::post('quickinquiry','HomeController@quickinquiry');
Route::post('upload-risk-profile-form','HomeController@uploadriskProfileForm');

Route::get('login',function(){
    return view('home_pages.login');
});
Route::get('registration',function(){
	return view('home_pages.register');
});

Route::get('invoice',function(){
    return view('home_pages.invoice');
});

Route::get('/service-detial/{id}','HomeController@subservice');

Route::get('forgot-password','ForgotPasswordController@forgotPassword');
Route::post('forgot-password','ForgotPasswordController@postForgotPassword');
Route::get('reset-password/{email}/{resetcode}','ForgotPasswordController@restetPassword');
Route::post('reset-password/{email}/{resetcode}','ForgotPasswordController@postResetPassword');

//Registration
Route::post('register-success','UserRegisterController@postRegister');
Route::get('activation/{email}/{code}','UserRegisterController@userActivation');
//Login
Route::post('gologin','LoginController@goLogin');
Route::get('validate','ValidationController@index');
Route::post('validate','ValidationController@validate2FA');
Route::get('logout','LoginController@logout');
//User
Route::group(['middleware' => ['User']], function () {

    // Route::get('dashboard','UserDashboardController@dashboard');
    // Route::get('profile_edit_user', 'ProfileController@edit');
    // Route::post('profile_details/{id}', 'ProfileController@update');
    // Route::post('change_password/{id}','ProfileController@password_update');
    // // profile
    // Route::post('profile_image/{id}', 'ProfileController@upload');
    Route::get('history','UserDashboardController@history');

});

// Super Admin
Route::group(['middleware' => ['SuperAdmin']], function () {
     Route::get('user-list','SuperAdminController@userList');
     Route::get('pack_act_de_act','SuperAdminController@pack_act_de_act');
    // profile
    Route::get('status-change/{id}','SuperAdminController@statusChange');
    Route::post('delete-user/{id}','SuperAdminController@deleteUser');
    //services
    Route::resource('services-list','ServiceController');
    Route::get('service-edit/{id}','ServiceController@edit');
    Route::post('service-update/{id}','ServiceController@update');
    Route::get('sub-services-list/{id}','ServiceController@subServiceList');
    //sub-services
    Route::resource('sub-service','SubServiceController');
    //blog
    Route::resource('super-admin-blog-section','BlogController');
    //news
    Route::resource('super-admin-news-section','NewsController');
    //Role Management section
    Route::resource('roles','RoleManagementController');
    //package section
    Route::resource('packages','PackageController');
    Route::get('sub-service-list/{id}','PackageController@subServiceList');
    //home-section
    Route::resource('manage-home-section','HomeSectionController');
    // Route::post('franchies/details/upload','StaffController@uploadFranchies')->name('upload.details');
    // Dsignation
    Route::resource('designation','DesignationController');
    
    Route::get('designation-slug/{slug}','StaffController@designationId');
    //Slider
    Route::get('slider-section','HomeSectionController@sliderSection');
    Route::get('add-slider','HomeSectionController@addSlider')->name('add-new-slider');
    Route::post('add-slider','HomeSectionController@postaddSlider')->name('added-slider');
    Route::get('edit-slider/{id}','HomeSectionController@editSlider')->name('edit-slider');
    Route::post('update-slider/{id}','HomeSectionController@updateSlider')->name('update-slider');
    Route::get('delete-slider/{id}','HomeSectionController@deleteSlider');
    //faq
    Route::resource('faq-list','FaqController');
    Route::get('faq-delete/{id}','FaqController@destroy');
    Route::post('faq-update/{id}','FaqController@update');
    Route::get('faq/{id}','FaqController@faqFind');
    
    //about us
    Route::resource('about-us','AboutUsController');
    //seeting
    Route::resource('setting','SettingController');
    Route::get('edit-limit','SettingController@edit_limit');
    Route::post('update-limit','SettingController@update_limit');
    Route::get('website-details','SettingController@edit_website_detials');
    Route::post('update-details','SettingController@update_details');
    Route::get('level-active','SettingController@levelActive');
    Route::get('update-level-active/{id}','SettingController@updateLevelActive');
    Route::get('staff-commission','SettingController@staffCommission');
    Route::post('update-commission','SettingController@updateCommission');
    Route::get('/franchise','FranchiseController@franchise');
    Route::get('promotion-staff','SuperAdminController@promtionStaff');
    Route::get('promoted-staff-name/{slug}','SuperAdminController@promotedStaff');
    Route::get('designation-role/{slug}','SuperAdminController@designationRole');
    Route::post('give-promotion-staff','SuperAdminController@givePromotionStaff');
    Route::get('invoice/{id}/{type}','PaymentController@invoice');
    Route::get('all-invoice','PaymentController@allInvioce');
    Route::post('all-invoice','PaymentController@allInvioce');
    Route::get('export-excel','PaymentController@exportExcel');
    Route::post('export-excel','PaymentController@exportExcel');
    Route::match(['get', 'post'],'filter-id-proof','StaffController@filterIdProof');
    //Deactivete
    Route::get('deactivate-staff/{id}','SuperAdminController@deactivateStaff');
    Route::get('role-level/{id}','SuperAdminController@rolelevel');
    Route::post('filter-role-level','SuperAdminController@filterRoleLevel');

    
});

Route::group(['middleware' => ['Telecaller']],function(){

    Route::get('lead','LeadController@genrateLead');
    Route::get('all-leads','LeadController@allLeads');
    Route::get('assigned-areas','FranchiseController@assignedAreas');
    Route::post('comment-lead','LeadController@commentLead');
});

Route::group(['middleware' => ['Franchise']],function(){
    Route::get('quick-inquiry','FranchiseController@quick_inquiry');
    Route::get('lead-assigned','FranchiseController@leadAssigned');
    Route::get('assigned-lead-staff/{id}','FranchiseController@leadAssignedStaff');
    Route::post('assigned-lead-staff','FranchiseController@postleadAssignedStaff');
    Route::get('lead/{id}','LeadController@staffLead');
    Route::get('assign-staff/{id}','FranchiseController@assignStaff');
    Route::post('assign-area','FranchiseController@assignArea');    
    Route::get('leads','FranchiseController@leads');
});

Route::group(['middleware' => ['Dashboard']],function(){

    Route::get('dashboard','SuperAdminController@superDashboard');
    //staff
    Route::resource('staff-manage','StaffController');
    Route::post('upload-details','StaffController@uploadstaffdetails');
    Route::get('staff-edit/{id}','StaffController@staffEdit');
    Route::get('approved/{id}','SuperAdminController@approvedByUpper');
    Route::get('staff-active/{id}','SuperAdminController@staffActivation');
    Route::get('staff-block/{id}','SuperAdminController@staffBlock');
    Route::get('staff-detial/{id}','StaffController@staffDetials');
    Route::post('staff-update/{id}','StaffController@staffUpdate');
    Route::get('child-staff/{id}','SuperAdminController@childStaff')->name('superadmin-childstaff');
    Route::get('chek-position/{id}','SuperAdminController@checkPosition');
    Route::get('payment-history','SuperAdminController@paymentHistory');
    Route::get('franchise-tc/{id}','StaffController@franchiseTc');
    //profile
    Route::get('profile-edit', 'ProfileController@edit');
    Route::post('profile-details/{id}', 'ProfileController@update');

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
   //
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Blog;
use Alert;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs_list = Blog::orderBy('id','desc')->get(); 
        return view('superadmin.blog.blog',compact('blogs_list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('superadmin.blog.blog_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $this->validate($request,[
            'title' => 'required',
            'sub_title' => 'required',
            'content'   =>  'required',
            'img'   =>  'required|mimes:jpeg,png,jpg,gif,svg'
        ]);

        $image = $request->file('img');
        $img_name = time().'.'.$image->getClientOriginalExtension();
        $path = public_path().'\assets\dashboard\upload\blog';
        $image->move($path, $img_name);

        $blog = new Blog;
        $blog->title = $request->title;
        $blog->sub_title = $request->sub_title;
        $blog->content = $request->content;
        $blog->img = $img_name;
        $blog->save();

        alert()->success('Blog Created','Blog created successfully.');
        return redirect('super-admin-blog-section');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::find($id);
        return view('superadmin.blog.blog_edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' =>  'required',
            'sub_title' =>  'required',
            'content'   =>  'required',
        ]);

        $blog = Blog::find($id);

        if ($request->hasFile('img')) {
            try{
                $image_path = public_path('assets/dashboard/upload/blog/').$blog->img;
                unlink($image_path);
            }catch(\ErrorException  $e){

            }

            $image = $request->file('img');
            $path = public_path('assets/dashboard/upload/blog/');
            $img_name = time().'.'.$image->getClientOriginalExtension();
            $image->move($path,$img_name); 

            $blog->img = $img_name;         
        }

        $blog->title = $request->title;
        $blog->sub_title = $request->sub_title;
        $blog->content = $request->content;
        $blog->update();

        alert()->success('Blog Edit','Blog Edit successfully.');
        return redirect('super-admin-blog-section');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = Blog::find($id);
        $blog->delete();

        alert()->success('Blog Delete','Blog Delted successfully.');
        return redirect('super-admin-blog-section');
    }
}

resources/views/superadmin/blog/blog.blade.php
@extends('layouts.dashboard.master')

@section('title') Blog | Dashboard @endsection

@section('style')    
	<link rel="stylesheet" type="text/css" href="{{ URL::asset('assets/dashboard/css/datatables.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('assets/dashboard/css/datatable-extension.css') }}" />
@endsection

@section('content')
 <div class="page-body user-management">
            <div class="container-fluid">
                <div class="page-header">
                    <div class="row">
                        <div class="col-lg-6">
                            <h5>Blog Management</h5>
                        </div>
                        <div class="col-lg-6">
                            <ol class="breadcrumb pull-right">
                                <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>                                
                                <li class="breadcrumb-item active">Blog Management</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Blog List</h5>
                                <a href="{{ route('super-admin-blog-section.create') }}" class="btn btn-primary pull-right">Add New</a>
                            </div>
                            <div class="card-body">
                                <div class="dt-ext table-responsive">
                                    <table id="export-button" class="display">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Title</th>
                                            <th>SubTitle</th>
                                            <th>Content</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        	@php $i=1; @endphp
                                        	@foreach($blogs_list as $blog)
                                        	<tr>
                                        		<td>{{ $i++ }}</td>
                                        		<td>{{ str_limit($blog['title'],100) }}</td>
                                        		<td>{{ str_limit($blog['sub_title'],150) }}</td>
                                        		<td>{{ str_limit($blog['content'],200) }}</td>
                                        		<td><img src="{{ URL::asset('assets\dashboard\upload\blog') }}\{{ $blog->img }}" alt="" height="100px" width="100px"></td>
                                        		<td>
                                        			<a href="{{ route('super-admin-blog-section.edit',$blog->id) }}" class="btn btn-primary"><i class="fa fa-pencil"></i> Edit</a>
                                        			<form action="{{ route('super-admin-blog-section.destroy',$blog->id) }}" method="post" accept-charset="utf-8">
                                        				{{ csrf_field() }}
                                        				{{ method_field('DELETE') }}
                                        				<button type="delete" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                                        			</form>
                                        		</td>
                                        	</tr>
                                        	@endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

@section('script')
<!--Datatable js-->
    <script src="{{ URL::asset('assets/dashboard/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/dashboard/js/datatable.custom.js') }}"></script>

<script>
$(document).ready( function () {
    $('#myTable').DataTable();
} );
</script>
@endsection

resources/views/superadmin/blog/blog_create.blade.php
@extends('layouts.dashboard.master')

@section('title') Blog-Create | Dashboard @endsection

@section('content')

<div class="page-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6">
                    <h5>Blog Create
                    </h5>
                </div>
                <div class="col-lg-6">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>                                
                        <li class="breadcrumb-item active">Blog cretae</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Create New Blog</h5>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <form class="form theme-form" action="{{ route('super-admin-blog-section.store') }}" method="post" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Blog Title</label>
                                        <div class="col-sm-9">
                                            <input type="text" name="title" class="form-control" placeholder="Type your title">
                                            @if($errors->has('title'))
                                                <strong class="text-danger">{{ $errors->first('title') }}</strong>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Blog Sub Title</label>
                                        <div class="col-sm-9">
                                            <input type="text" name="sub_title" class="form-control" placeholder="Type your sub title">
                                            @if($errors->has('sub_title'))
                                                <strong class="text-danger">{{ $errors->first('sub_title') }}</strong>
                                            @endif
                                        </div>
                                    </div>                                    
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Description</label>
                                        <div class="col-sm-9">
                                            <textarea rows="7" cols="5" name="content" class="form-control" placeholder="Type your Description"></textarea>
                                            @if($errors->has('content'))
                                                <strong class="text-danger">{{ $errors->first('content') }}</strong>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Upload File</label>
                                        <div class="col-sm-9">
                                            <input type="file" name="img" class="form-control">
                                            @if($errors->has('img'))
                                                <strong class="text-danger">{{ $errors->first('img') }}</strong>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="col-sm-9 offset-sm-3">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                            <a href="{{ url('super-admin-blog-section') }}" class="btn btn-light">Cancel</a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/superadmin/blog/blog_edit.blade.php
@extends('layouts.dashboard.master')

@section('title') Blog-Edit | Dashboard @endsection

@section('content')

<div class="page-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6">
                    <h5>Blog Edit
                    </h5>
                </div>
                <div class="col-lg-6">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="{{ url('dashboard') }}"><i class="fa fa-home"></i></a></li>                                
                        <li class="breadcrumb-item active">Blog Edit</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Blog Edit</h5>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <form class="form theme-form" action="{{ route('super-admin-blog-section.update',$blog->id) }}" method="post" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    {{ method_field('PATCH') }}
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Blog Title</label>
                                        <div class="col-sm-9">
                                            <input type="text" name="title" class="form-control" value="{{ $blog->title }}" placeholder="Type your title">
                                            @if($errors->has('title'))
                                                <strong class="text-danger">{{ $errors->first('title') }}</strong>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Blog Sub Title</label>
                                        <div class="col-sm-9">
                                            <input type="text" name="sub_title" class="form-control" value="{{ $blog->sub_title }}" placeholder="Type your sub title">
                                            @if($errors->has('sub_title'))
                                                <strong class="text-danger">{{ $errors->first('sub_title') }}</strong>
                                            @endif
                                        </div>
                                    </div>                                    
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Description</label>
                                        <div class="col-sm-9">
                                            <textarea rows="7" cols="5" name="content" class="form-control" placeholder="Type your Description">{{ $blog->content }}</textarea>
                                            @if($errors->has('content'))
                                                <strong class="text-danger">{{ $errors->first('content') }}</strong>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Upload File</label>
                                        <div class="col-sm-4">
                                            <input type="file" name="img" class="form-control" value="{{ $blog->img }}">
                                            @if($errors->has('img'))
                                                <strong class="text-danger">{{ $errors->first('img') }}</strong>
                                            @endif
                                        </div>
                                        <div class="col-sm-4">
                                            <img src="{{ URL::asset('assets\dashboard\upload\blog') }}\{{ $blog->img }}" height="150px" width="150px" alt="">
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="col-sm-9 offset-sm-3">
                                            <button type="submit" class="btn btn-primary">Update</button>
                                            <a href="{{ url('super-admin-blog-section') }}" class="btn btn-light">Cancel</a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection