routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
Route::get('/','HomeController@index');
Route::get('about','HomeController@about');
Route::get('faq','HomeController@faq');
Route::get('contact','HomeController@contact');
Route::get('service','HomeController@service');
Route::get('chart','HomeController@chart');
Route::get('pricing','HomeController@pricing');
Route::get('technical-analysis','HomeController@technicalAnalysis');
Route::get('stock-chart','HomeController@stockChart');
Route::get('news','HomeController@news');
Route::get('explore','HomeController@explore');
Route::get('complain','HomeController@complain');
Route::get('refund-policy','HomeController@refundPolice');
Route::get('risk-discloser','HomeController@riskdiscloser');
Route::get('disclaimer','HomeController@disclaimer');
Route::get('terms_condition','HomeController@terms_condition');
Route::get('reviews','HomeController@reviews');
Route::get('risk-profile','HomeController@risk_profile');
Route::get('kyc','HomeController@kyc');
Route::get('kyc-individual','HomeController@kycIndividual');
Route::post('/kyc-Post-individual','KycController@Individual');
Route::post('/kyc-Post-Non-Individual','Kyc_Non_Individual_Controller@Non_Individual');
Route::get('kyc-non-individual','HomeController@kycNonIndividual');
Route::get('download_individual','KycController@getDownload');
Route::get('download_non_individual','Kyc_Non_Individual_Controller@getDownload');
Route::post('/upload_kyc_form','Upload_Kyc_Form_Controller@upload_kyc_form');
Route::get('risk-profile-form','HomeController@riskProfileForm');
Route::get('/blog','HomeController@blog');
Route::get('blog-detail/{id}','HomeController@blogDetail');
Route::get('news-detail/{id}','HomeController@newsDetail');
Route::get('service/{service}','HomeController@serviceList')->name('list.service');
Route::get('state/{id}','HomeController@stateId');
Route::get('city/{id}','HomeController@cityId');
Route::post('quickinquiry','HomeController@quickinquiry');
Route::post('upload-risk-profile-form','HomeController@uploadriskProfileForm');

Route::get('login',function(){
    return view('home_pages.login');
});
Route::get('registration',function(){
	return view('home_pages.register');
});

Route::get('invoice',function(){
    return view('home_pages.invoice');
});

Route::get('/service-detial/{id}','HomeController@subservice');

Route::get('forgot-password','ForgotPasswordController@forgotPassword');
Route::post('forgot-password','ForgotPasswordController@postForgotPassword');
Route::get('reset-password/{email}/{resetcode}','ForgotPasswordController@restetPassword');
Route::post('reset-password/{email}/{resetcode}','ForgotPasswordController@postResetPassword');

//Registration
Route::post('register-success','UserRegisterController@postRegister');
Route::get('activation/{email}/{code}','UserRegisterController@userActivation');
//Login
Route::post('gologin','LoginController@goLogin');
Route::get('validate','ValidationController@index');
Route::post('validate','ValidationController@validate2FA');
Route::get('logout','LoginController@logout');
//User
Route::group(['middleware' => ['User']], function () {

    // Route::get('dashboard','UserDashboardController@dashboard');
    // Route::get('profile_edit_user', 'ProfileController@edit');
    // Route::post('profile_details/{id}', 'ProfileController@update');
    // Route::post('change_password/{id}','ProfileController@password_update');
    // // profile
    // Route::post('profile_image/{id}', 'ProfileController@upload');
    Route::get('history','UserDashboardController@history');

});

// Super Admin
Route::group(['middleware' => ['SuperAdmin']], function () {
     Route::get('user-list','SuperAdminController@userList');
     Route::get('pack_act_de_act','SuperAdminController@pack_act_de_act');
    // profile
    Route::get('status-change/{id}','SuperAdminController@statusChange');
    Route::post('delete-user/{id}','SuperAdminController@deleteUser');
    //services
    Route::resource('services-list','ServiceController');
    Route::get('service-edit/{id}','ServiceController@edit');
    Route::post('service-update/{id}','ServiceController@update');
    Route::get('sub-services-list/{id}','ServiceController@subServiceList');
    //sub-services
    Route::resource('sub-service','SubServiceController');
    //blog
    Route::resource('super-admin-blog-section','BlogController');
    //news
    Route::resource('super-admin-news-section','NewsController');
    //Role Management section
    Route::resource('roles','RoleManagementController');
    //package section
    Route::resource('packages','PackageController');
    Route::get('sub-service-list/{id}','PackageController@subServiceList');
    //home-section
    Route::resource('manage-home-section','HomeSectionController');
    // Route::post('franchies/details/upload','StaffController@uploadFranchies')->name('upload.details');
    // Dsignation
    Route::resource('designation','DesignationController');
    
    Route::get('designation-slug/{slug}','StaffController@designationId');
    //Slider
    Route::get('slider-section','HomeSectionController@sliderSection');
    Route::get('add-slider','HomeSectionController@addSlider')->name('add-new-slider');
    Route::post('add-slider','HomeSectionController@postaddSlider')->name('added-slider');
    Route::get('edit-slider/{id}','HomeSectionController@editSlider')->name('edit-slider');
    Route::post('update-slider/{id}','HomeSectionController@updateSlider')->name('update-slider');
    Route::get('delete-slider/{id}','HomeSectionController@deleteSlider');
    //faq
    Route::resource('faq-list','FaqController');
    Route::get('faq-delete/{id}','FaqController@destroy');
    Route::post('faq-update/{id}','FaqController@update');
    Route::get('faq/{id}','FaqController@faqFind');
    
    //about us
    Route::resource('about-us','AboutUsController');
    //seeting
    Route::resource('setting','SettingController');
    Route::get('edit-limit','SettingController@edit_limit');
    Route::post('update-limit','SettingController@update_limit');
    Route::get('website-details','SettingController@edit_website_detials');
    Route::post('update-details','SettingController@update_details');
    Route::get('level-active','SettingController@levelActive');
    Route::get('update-level-active/{id}','SettingController@updateLevelActive');
    Route::get('staff-commission','SettingController@staffCommission');
    Route::post('update-commission','SettingController@updateCommission');
    Route::get('/franchise','FranchiseController@franchise');
    Route::get('promotion-staff','SuperAdminController@promtionStaff');
    Route::get('promoted-staff-name/{slug}','SuperAdminController@promotedStaff');
    Route::get('designation-role/{slug}','SuperAdminController@designationRole');
    Route::post('give-promotion-staff','SuperAdminController@givePromotionStaff');
    Route::get('invoice/{id}/{type}','PaymentController@invoice');
    Route::get('all-invoice','PaymentController@allInvioce');
    Route::post('all-invoice','PaymentController@allInvioce');
    Route::get('export-excel','PaymentController@exportExcel');
    Route::post('export-excel','PaymentController@exportExcel');
    Route::match(['get', 'post'],'filter-id-proof','StaffController@filterIdProof');
    //Deactivete
    Route::get('deactivate-staff/{id}','SuperAdminController@deactivateStaff');
    Route::get('role-level/{id}','SuperAdminController@rolelevel');
    Route::post('filter-role-level','SuperAdminController@filterRoleLevel');

    
});

Route::group(['middleware' => ['Telecaller']],function(){

    Route::get('lead','LeadController@genrateLead');
    Route::get('all-leads','LeadController@allLeads');
    Route::get('assigned-areas','FranchiseController@assignedAreas');
    Route::post('comment-lead','LeadController@commentLead');
});

Route::group(['middleware' => ['Franchise']],function(){
    Route::get('quick-inquiry','FranchiseController@quick_inquiry');
    Route::get('lead-assigned','FranchiseController@leadAssigned');
    Route::get('assigned-lead-staff/{id}','FranchiseController@leadAssignedStaff');
    Route::post('assigned-lead-staff','FranchiseController@postleadAssignedStaff');
    Route::get('lead/{id}','LeadController@staffLead');
    Route::get('assign-staff/{id}','FranchiseController@assignStaff');
    Route::post('assign-area','FranchiseController@assignArea');    
    Route::get('leads','FranchiseController@leads');
});

Route::group(['middleware' => ['Dashboard']],function(){

    Route::get('dashboard','SuperAdminController@superDashboard');
    //staff
    Route::resource('staff-manage','StaffController');
    Route::post('upload-details','StaffController@uploadstaffdetails');
    Route::get('staff-edit/{id}','StaffController@staffEdit');
    Route::get('approved/{id}','SuperAdminController@approvedByUpper');
    Route::get('staff-active/{id}','SuperAdminController@staffActivation');
    Route::get('staff-block/{id}','SuperAdminController@staffBlock');
    Route::get('staff-detial/{id}','StaffController@staffDetials');
    Route::post('staff-update/{id}','StaffController@staffUpdate');
    Route::get('child-staff/{id}','SuperAdminController@childStaff')->name('superadmin-childstaff');
    Route::get('chek-position/{id}','SuperAdminController@checkPosition');
    Route::get('payment-history','SuperAdminController@paymentHistory');
    Route::get('franchise-tc/{id}','StaffController@franchiseTc');
    //profile
    Route::get('profile-edit', 'ProfileController@edit');
    Route::post('profile-details/{id}', 'ProfileController@update');

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    public function sub_service()
    {
    	return $this->hasMany('App\Models\SubService','service_id','id')->where('is_delete',0);
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Service;
use App\Models\SubService;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::orderBy('id','desc')->get();
        return view('superadmin.service.service_list',compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $service = Service::find($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

        $image = $request->file('image');
        $img_name = time().'.'.$image->getClientOriginalExtension();
        $path = public_path().'/assets/dashboard/upload/service';
        $image->move($path, $img_name);

        $service = Service::find($id);
        $service->name = $request->service;
        $service->image = $img_name;
        $service->update();

        alert()->success('Successfully update service.');
        return redirect('services-list');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
        //
    }

     public function subServiceList($id)
    {
        $service = Service::find($id);
        $sub_service = SubService::where('service_id',$id)->orderBy('id','desc')->where('is_delete',0)->get();
        return view('superadmin.service.sub_service_list',compact('sub_service','service'));
    }

}

resources/views/superadmin/service/service_list.blade.php
@extends('layouts.dashboard.master')

@section('title') Services List|Dashboard @endsection

@section('style')
<style type="text/css" media="screen">
.error {
    margin: 0px!important;
    color: #ff2b2b!important;
}
p {
    font-size: 16px!important;
}   
</style>
@endsection

@section('content')
<div class="page-body user-management">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6">
                    <h5>Services List</h5>
                </div>
                <div class="col-lg-6">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>                                
                        <li class="breadcrumb-item active">Services List</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>All Services</h5>
                        <!-- <a href="{{ route('super-admin-news-section.create') }}" class="btn btn-primary pull-right">Add New</a> -->
                    </div>
                    <div class="card-body">
                        <div class="dt-ext table-responsive">
                            <table id="export-button" class="display">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Image</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                	@php $i=1; @endphp
                                	@foreach($services as $serve)
                                		<tr>
                                			<td>{{ $i++ }}</td>
                                			<td>{{ $serve->name }}</td>
                                            <td><img src="{{ URL::asset('assets/dashboard/upload/service') }}/{{ $serve->image }}" alt="" height="100px" width="100px"> </td>
                                			<td><a href="{{ url('sub-services-list') }}/{{ $serve->id }}" class="btn btn-primary" title="">Details</a>
                                                <a href="#" class="btn btn-info" onclick="modelpopop({{$serve->id}})" data-toggle="modal" data-target="#serviceModel">Edit</a></td>
                                		</tr>
                                	@endforeach                                          
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="serviceModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Edit Service</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form class="serviceModel" action="" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label" >Service:</label>
                                <input type="text" class="form-control" id="service" name="service">
                            </div>
                            <div class="form-group">
                                <label for="message-text" class="col-form-label">Image:</label>
                                <input type="file" id="image" name="image" class="form-control">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script type="text/javascript">

$(document).ready(function () {

    $('.serviceModel').validate({ // initialize the plugin
        rules: {
            service: {
                required: true,
            }
        }
    });
});
  function modelpopop(id)
{
    // console.log(id);
        $.ajax({
            method: 'GET',
            url: '/service-edit/'+id, 

            success: function(response){ 
                console.log(response);
                $('.serviceModel').attr('action', "{{url('/service-update')}}/"+id);
                $('#service').val(response.name);
                // $('#image').val(response.image);
                
           },
            error: function(jqXHR, textStatus, errorThrown) { 
                console.log("error");
            }
        });
}
</script>

@endsection

resources/views/superadmin/service/sub_service_list.blade.php
@extends('layouts.dashboard.master')

@section('title') Sub Services List|Dashboard @endsection

@section('content')
<div class="page-body user-management">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6">
                    <h5>{{ $service->name }} LIST
                    </h5>
                </div>
                <div class="col-lg-6">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>                                
                        <li class="breadcrumb-item active">Service</li>
                        <li class="breadcrumb-item active">{{ strtolower($service->name) }} List</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>{{ $service->name }} Service</h5>
                        <a href="{{ route('sub-service.index') }}" class="btn btn-primary pull-right">Create Service</a>
                    </div>
                    <div class="card-body">
                        <div class="dt-ext table-responsive">
                            <table id="export-button" class="display">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Title</th>
                                    <th>Capital Amount</th>
                                    <th>Profit Amount</th>
                                    <!-- <th>Service Details</th> -->
                                    <th>Duration</th>
                                    <!-- <th>Sample Call</th> -->
                                    <!-- <th>Updates</th> -->
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                	@php $i=1; @endphp
                                	@foreach($sub_service as $service)
                                		<tr>
                                			<td>{{ $i++ }}</td>
                                			<td>{{ $service->name }}</td>
                                            <td>{{ $service->capital }}</td>
                                            <td>{{ $service->profit }}</td>
                                            <!-- <td>@php echo substr($service['service_details'],0) @endphp</td> -->
                                            <td>{{ $service->duration_from }} To {{ $service->duration_to }} Days</td>
                                            <!-- <td>@php echo $service->sample_call @endphp</td> -->
                                            <!-- <td>@php echo $service->updates @endphp</td> -->
                                            <td><a href="{{ route('sub-service.edit',$service->id) }}"  class="btn btn-primary">Edit</a>
                                                <form action="{{ route('sub-service.destroy',$service->id) }}" method="post">
                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}
                                                    <button class="btn btn-danger delete">Delete</button>
                                                </form>
                                            </td>
                                		</tr>
                                	@endforeach                                          
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')

@endsection