routes/web.php
Route::get('risk-discloser','HomeController@riskdiscloser');
Route::get('disclaimer','HomeController@disclaimer');
Route::get('terms_condition','HomeController@terms_condition');
Route::get('reviews','HomeController@reviews');
Route::get('risk-profile','HomeController@risk_profile');
Route::get('kyc','HomeController@kyc');
Route::get('kyc-individual','HomeController@kycIndividual');
Route::post('/kyc-Post-individual','KycController@Individual');
Route::post('/kyc-Post-Non-Individual','Kyc_Non_Individual_Controller@Non_Individual');
Route::get('kyc-non-individual','HomeController@kycNonIndividual');
Route::get('download_individual','KycController@getDownload');
Route::get('download_non_individual','Kyc_Non_Individual_Controller@getDownload');
Route::post('/upload_kyc_form','Upload_Kyc_Form_Controller@upload_kyc_form');
Route::get('risk-profile-form','HomeController@riskProfileForm');
Route::get('/blog','HomeController@blog');
Route::get('blog-detail/{id}','HomeController@blogDetail');
Route::get('news-detail/{id}','HomeController@newsDetail');
Route::get('service/{service}','HomeController@serviceList')->name('list.service');
Route::get('state/{id}','HomeController@stateId');
Route::get('city/{id}','HomeController@cityId');
Route::post('quickinquiry','HomeController@quickinquiry');
Route::post('upload-risk-profile-form','HomeController@uploadriskProfileForm');

Route::get('login',function(){
    return view('home_pages.login');
});
Route::get('registration',function(){
	return view('home_pages.register');
});

Route::get('invoice',function(){
    return view('home_pages.invoice');
});

Route::get('/service-detial/{id}','HomeController@subservice');

Route::get('forgot-password','ForgotPasswordController@forgotPassword');
Route::post('forgot-password','ForgotPasswordController@postForgotPassword');
Route::get('reset-password/{email}/{resetcode}','ForgotPasswordController@restetPassword');
Route::post('reset-password/{email}/{resetcode}','ForgotPasswordController@postResetPassword');

//Registration
Route::post('register-success','UserRegisterController@postRegister');
Route::get('activation/{email}/{code}','UserRegisterController@userActivation');
//Login
Route::post('gologin','LoginController@goLogin');
Route::get('validate','ValidationController@index');
Route::post('validate','ValidationController@validate2FA');
Route::get('logout','LoginController@logout');
//User
Route::group(['middleware' => ['User']], function () {

    // Route::get('dashboard','UserDashboardController@dashboard');
    // Route::get('profile_edit_user', 'ProfileController@edit');
    // Route::post('profile_details/{id}', 'ProfileController@update');
    // Route::post('change_password/{id}','ProfileController@password_update');
    // // profile
    // Route::post('profile_image/{id}', 'ProfileController@upload');
    Route::get('history','UserDashboardController@history');

});

// Super Admin
Route::group(['middleware' => ['SuperAdmin']], function () {
     Route::get('user-list','SuperAdminController@userList');
     Route::get('pack_act_de_act','SuperAdminController@pack_act_de_act');
    // profile
    Route::get('status-change/{id}','SuperAdminController@statusChange');
    Route::post('delete-user/{id}','SuperAdminController@deleteUser');
    //services
    Route::resource('services-list','ServiceController');
    Route::get('service-edit/{id}','ServiceController@edit');
    Route::post('service-update/{id}','ServiceController@update');
    Route::get('sub-services-list/{id}','ServiceController@subServiceList');
    //sub-services
    Route::resource('sub-service','SubServiceController');
    //blog
    Route::resource('super-admin-blog-section','BlogController');
    //news
    Route::resource('super-admin-news-section','NewsController');
    //Role Management section
    Route::resource('roles','RoleManagementController');
    //package section
    Route::resource('packages','PackageController');
    Route::get('sub-service-list/{id}','PackageController@subServiceList');
    //home-section
    Route::resource('manage-home-section','HomeSectionController');
    // Route::post('franchies/details/upload','StaffController@uploadFranchies')->name('upload.details');
    // Dsignation
    Route::resource('designation','DesignationController');
    
    Route::get('designation-slug/{slug}','StaffController@designationId');
    //Slider
    Route::get('slider-section','HomeSectionController@sliderSection');
    Route::get('add-slider','HomeSectionController@addSlider')->name('add-new-slider');
    Route::post('add-slider','HomeSectionController@postaddSlider')->name('added-slider');
    Route::get('edit-slider/{id}','HomeSectionController@editSlider')->name('edit-slider');
    Route::post('update-slider/{id}','HomeSectionController@updateSlider')->name('update-slider');
    Route::get('delete-slider/{id}','HomeSectionController@deleteSlider');
    //faq
    Route::resource('faq-list','FaqController');
    Route::get('faq-delete/{id}','FaqController@destroy');
    Route::post('faq-update/{id}','FaqController@update');
    Route::get('faq/{id}','FaqController@faqFind');
    
    //about us
    Route::resource('about-us','AboutUsController');
    //seeting
    Route::resource('setting','SettingController');
    Route::get('edit-limit','SettingController@edit_limit');
    Route::post('update-limit','SettingController@update_limit');
    Route::get('website-details','SettingController@edit_website_detials');
    Route::post('update-details','SettingController@update_details');
    Route::get('level-active','SettingController@levelActive');
    Route::get('update-level-active/{id}','SettingController@updateLevelActive');
    Route::get('staff-commission','SettingController@staffCommission');
    Route::post('update-commission','SettingController@updateCommission');
    Route::get('/franchise','FranchiseController@franchise');
    Route::get('promotion-staff','SuperAdminController@promtionStaff');
    Route::get('promoted-staff-name/{slug}','SuperAdminController@promotedStaff');
    Route::get('designation-role/{slug}','SuperAdminController@designationRole');
    Route::post('give-promotion-staff','SuperAdminController@givePromotionStaff');
    Route::get('invoice/{id}/{type}','PaymentController@invoice');
    Route::get('all-invoice','PaymentController@allInvioce');
    Route::post('all-invoice','PaymentController@allInvioce');
    Route::get('export-excel','PaymentController@exportExcel');
    Route::post('export-excel','PaymentController@exportExcel');
    Route::match(['get', 'post'],'filter-id-proof','StaffController@filterIdProof');
    //Deactivete
    Route::get('deactivate-staff/{id}','SuperAdminController@deactivateStaff');
    Route::get('role-level/{id}','SuperAdminController@rolelevel');
    Route::post('filter-role-level','SuperAdminController@filterRoleLevel');

    
});

Route::group(['middleware' => ['Telecaller']],function(){

    Route::get('lead','LeadController@genrateLead');
    Route::get('all-leads','LeadController@allLeads');
    Route::get('assigned-areas','FranchiseController@assignedAreas');
    Route::post('comment-lead','LeadController@commentLead');
});

Route::group(['middleware' => ['Franchise']],function(){
    Route::get('quick-inquiry','FranchiseController@quick_inquiry');
    Route::get('lead-assigned','FranchiseController@leadAssigned');
    Route::get('assigned-lead-staff/{id}','FranchiseController@leadAssignedStaff');
    Route::post('assigned-lead-staff','FranchiseController@postleadAssignedStaff');
    Route::get('lead/{id}','LeadController@staffLead');
    Route::get('assign-staff/{id}','FranchiseController@assignStaff');
    Route::post('assign-area','FranchiseController@assignArea');    
    Route::get('leads','FranchiseController@leads');
});

Route::group(['middleware' => ['Dashboard']],function(){

    Route::get('dashboard','SuperAdminController@superDashboard');
    //staff
    Route::resource('staff-manage','StaffController');
    Route::post('upload-details','StaffController@uploadstaffdetails');
    Route::get('staff-edit/{id}','StaffController@staffEdit');
    Route::get('approved/{id}','SuperAdminController@approvedByUpper');
    Route::get('staff-active/{id}','SuperAdminController@staffActivation');
    Route::get('staff-block/{id}','SuperAdminController@staffBlock');
    Route::get('staff-detial/{id}','StaffController@staffDetials');
    Route::post('staff-update/{id}','StaffController@staffUpdate');
    Route::get('child-staff/{id}','SuperAdminController@childStaff')->name('superadmin-childstaff');
    Route::get('chek-position/{id}','SuperAdminController@checkPosition');
    Route::get('payment-history','SuperAdminController@paymentHistory');
    Route::get('franchise-tc/{id}','StaffController@franchiseTc');
    //profile
    Route::get('profile-edit', 'ProfileController@edit');
    Route::post('profile-details/{id}', 'ProfileController@update');
    Route::post('profile-image/{id}', 'ProfileController@upload');
    Route::post('change-password/{id}','ProfileController@password_update');
    //delete staff
    Route::get('delete-staff/{id}','SuperAdminController@deletestaff');
    Route::get('delete-approve/{id}','SuperAdminController@approveDeleteReviewer');
    Route::get('delete-cancel/{id}','SuperAdminController@deleteCancel');
    Route::get('designation-id/{slug}','StaffController@designationfind');

    Route::get('staff-level/{level}','SuperAdminController@staffLevel');
    Route::get('revenue-list','SuperAdminController@revenuelist');
    Route::post('filter-payment-history','PaymentController@filterPaymentHistory');
    Route::post('filter-leads','LeadController@filterleads');
    
});

Route::get('pay/{pack_id}/{package}','PaymentController@pay');
Route::post('payment','PaymentController@payment');
Route::get('pay-now/{id}','PaymentController@paymentComplete');

Route::get('/pay_form', function () {
    return view('home_pages.pay_form');
});
// Newsletter

resources/views/staff/staff_list.blade.php
@extends('layouts.dashboard.master')

@section('title') Staff | Dashboard @endsection

@section('style')    
	<link rel="stylesheet" type="text/css" href="{{ URL::asset('assets/dashboard/css/datatables.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('assets/dashboard/css/datatable-extension.css') }}" />
@endsection

@section('content')
 <div class="page-body user-management">
            <div class="container-fluid">
                <div class="page-header">
                    <div class="row">
                        <div class="col-lg-6">
                            <h5>Staff Management
                            </h5>
                        </div>
                        <div class="col-lg-6">
                            <ol class="breadcrumb pull-right">
                                <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>                                
                                <li class="breadcrumb-item active">Staff Management</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Staff Management</h5>
                                <a href="{{ route('staff-manage.create') }}" class="btn btn-primary pull-right">Add Staff</a>
                            </div>
                            <div class="card-body">
                                <div class="dt-ext table-responsive">
                                    <table id="export-button" class="display">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Position</th>
                                            <th>Status</th>
                                            <th>Details</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                          @php $i=1; @endphp

                                          @foreach($staff as $staf)
                                            <tr>
                                                <td>{{ $i++ }}</td>
                                                <td>{{ $staf->user_name }}</td>
                                                <td>@if(isset($staf->designation->post))
                                                {{ $staf->designation->post }}@endif</td>
                                                <td>@if($staf->status == 0)
                                                    <span class="badge badge-primary">New Join</span> @elseif($staf->status == 1)
                                                    <span class="badge badge-success">Active</span>
                                                    @endif
                                                </td>
                                                <td><a href="{{ url('staff-detial') }}/{{ $staf->id }}" class="btn btn-primary">Details</a></td>
                                                <td><a href="{{ url('staff-edit') }}/{{ $staf->id }}" class="btn btn-info"><i class="fa fa-pencil"></i>&nbsp; Edit</a>
                                                    <!-- <a href="{{ url('staff-delete') }}/{{ $staf->id }}" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i>&nbsp; Delete</a> --></td>
                                            </tr>
                                          @endforeach
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection