routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
Route::get('/','HomeController@index');
Route::get('about','HomeController@about');
Route::get('faq','HomeController@faq');
Route::get('contact','HomeController@contact');
Route::get('service','HomeController@service');
Route::get('chart','HomeController@chart');
Route::get('pricing','HomeController@pricing');
Route::get('technical-analysis','HomeController@technicalAnalysis');
Route::get('stock-chart','HomeController@stockChart');
Route::get('news','HomeController@news');
Route::get('explore','HomeController@explore');
Route::get('complain','HomeController@complain');
Route::get('refund-policy','HomeController@refundPolice');
Route::get('risk-discloser','HomeController@riskdiscloser');
Route::get('disclaimer','HomeController@disclaimer');
Route::get('terms_condition','HomeController@terms_condition');
Route::get('reviews','HomeController@reviews');
Route::get('risk-profile','HomeController@risk_profile');
Route::get('kyc','HomeController@kyc');
Route::get('kyc-individual','HomeController@kycIndividual');
Route::post('/kyc-Post-individual','KycController@Individual');
Route::post('/kyc-Post-Non-Individual','Kyc_Non_Individual_Controller@Non_Individual');
Route::get('kyc-non-individual','HomeController@kycNonIndividual');
Route::get('download_individual','KycController@getDownload');
Route::get('download_non_individual','Kyc_Non_Individual_Controller@getDownload');
Route::post('/upload_kyc_form','Upload_Kyc_Form_Controller@upload_kyc_form');
Route::get('risk-profile-form','HomeController@riskProfileForm');
Route::get('/blog','HomeController@blog');
Route::get('blog-detail/{id}','HomeController@blogDetail');
Route::get('news-detail/{id}','HomeController@newsDetail');
Route::get('service/{service}','HomeController@serviceList')->name('list.service');
Route::get('state/{id}','HomeController@stateId');
Route::get('city/{id}','HomeController@cityId');
Route::post('quickinquiry','HomeController@quickinquiry');
Route::post('upload-risk-profile-form','HomeController@uploadriskProfileForm');

Route::get('login',function(){
    return view('home_pages.login');
});
Route::get('registration',function(){
	return view('home_pages.register');
});

Route::get('invoice',function(){
    return view('home_pages.invoice');
});

Route::get('/service-detial/{id}','HomeController@subservice');

Route::get('forgot-password','ForgotPasswordController@forgotPassword');
Route::post('forgot-password','ForgotPasswordController@postForgotPassword');
Route::get('reset-password/{email}/{resetcode}','ForgotPasswordController@restetPassword');
Route::post('reset-password/{email}/{resetcode}','ForgotPasswordController@postResetPassword');

//Registration
Route::post('register-success','UserRegisterController@postRegister');
Route::get('activation/{email}/{code}','UserRegisterController@userActivation');
//Login
Route::post('gologin','LoginController@goLogin');
Route::get('validate','ValidationController@index');
Route::post('validate','ValidationController@validate2FA');
Route::get('logout','LoginController@logout');
//User
Route::group(['middleware' => ['User']], function () {

    // Route::get('dashboard','UserDashboardController@dashboard');
    // Route::get('profile_edit_user', 'ProfileController@edit');
    // Route::post('profile_details/{id}', 'ProfileController@update');
    // Route::post('change_password/{id}','ProfileController@password_update');
    // // profile
    // Route::post('profile_image/{id}', 'ProfileController@upload');
    Route::get('history','UserDashboardController@history');

});

// Super Admin
Route::group(['middleware' => ['SuperAdmin']], function () {
     Route::get('user-list','SuperAdminController@userList');
     Route::get('pack_act_de_act','SuperAdminController@pack_act_de_act');
    // profile
    Route::get('status-change/{id}','SuperAdminController@statusChange');
    Route::post('delete-user/{id}','SuperAdminController@deleteUser');
    //services
    Route::resource('services-list','ServiceController');
    Route::get('service-edit/{id}','ServiceController@edit');
    Route::post('service-update/{id}','ServiceController@update');
    Route::get('sub-services-list/{id}','ServiceController@subServiceList');
    //sub-services
    Route::resource('sub-service','SubServiceController');
    //blog
    Route::resource('super-admin-blog-section','BlogController');
    //news
    Route::resource('super-admin-news-section','NewsController');
    //Role Management section
    Route::resource('roles','RoleManagementController');
    //package section
    Route::resource('packages','PackageController');
    Route::get('sub-service-list/{id}','PackageController@subServiceList');
    //home-section
    Route::resource('manage-home-section','HomeSectionController');
    // Route::post('franchies/details/upload','StaffController@uploadFranchies')->name('upload.details');
    // Dsignation
    Route::resource('designation','DesignationController');
    
    Route::get('designation-slug/{slug}','StaffController@designationId');
    //Slider
    Route::get('slider-section','HomeSectionController@sliderSection');
    Route::get('add-slider','HomeSectionController@addSlider')->name('add-new-slider');
    Route::post('add-slider','HomeSectionController@postaddSlider')->name('added-slider');
    Route::get('edit-slider/{id}','HomeSectionController@editSlider')->name('edit-slider');
    Route::post('update-slider/{id}','HomeSectionController@updateSlider')->name('update-slider');
    Route::get('delete-slider/{id}','HomeSectionController@deleteSlider');
    //faq
    Route::resource('faq-list','FaqController');
    Route::get('faq-delete/{id}','FaqController@destroy');
    Route::post('faq-update/{id}','FaqController@update');
    Route::get('faq/{id}','FaqController@faqFind');
    
    //about us
    Route::resource('about-us','AboutUsController');
    //seeting
    Route::resource('setting','SettingController');
    Route::get('edit-limit','SettingController@edit_limit');
    Route::post('update-limit','SettingController@update_limit');
    Route::get('website-details','SettingController@edit_website_detials');
    Route::post('update-details','SettingController@update_details');
    Route::get('level-active','SettingController@levelActive');
    Route::get('update-level-active/{id}','SettingController@updateLevelActive');
    Route::get('staff-commission','SettingController@staffCommission');
    Route::post('update-commission','SettingController@updateCommission');
    Route::get('/franchise','FranchiseController@franchise');
    Route::get('promotion-staff','SuperAdminController@promtionStaff');
    Route::get('promoted-staff-name/{slug}','SuperAdminController@promotedStaff');
    Route::get('designation-role/{slug}','SuperAdminController@designationRole');
    Route::post('give-promotion-staff','SuperAdminController@givePromotionStaff');
    Route::get('invoice/{id}/{type}','PaymentController@invoice');
    Route::get('all-invoice','PaymentController@allInvioce');
    Route::post('all-invoice','PaymentController@allInvioce');
    Route::get('export-excel','PaymentController@exportExcel');
    Route::post('export-excel','PaymentController@exportExcel');
    Route::match(['get', 'post'],'filter-id-proof','StaffController@filterIdProof');
    //Deactivete
    Route::get('deactivate-staff/{id}','SuperAdminController@deactivateStaff');
    Route::get('role-level/{id}','SuperAdminController@rolelevel');
    Route::post('filter-role-level','SuperAdminController@filterRoleLevel');

    
});

Route::group(['middleware' => ['Telecaller']],function(){

    Route::get('lead','LeadController@genrateLead');
    Route::get('all-leads','LeadController@allLeads');
    Route::get('assigned-areas','FranchiseController@assignedAreas');
    Route::post('comment-lead','LeadController@commentLead');
});

Route::group(['middleware' => ['Franchise']],function(){
    Route::get('quick-inquiry','FranchiseController@quick_inquiry');
    Route::get('lead-assigned','FranchiseController@leadAssigned');
    Route::get('assigned-lead-staff/{id}','FranchiseController@leadAssignedStaff');
    Route::post('assigned-lead-staff','FranchiseController@postleadAssignedStaff');
    Route::get('lead/{id}','LeadController@staffLead');
    Route::get('assign-staff/{id}','FranchiseController@assignStaff');
    Route::post('assign-area','FranchiseController@assignArea');    
    Route::get('leads','FranchiseController@leads');
});

Route::group(['middleware' => ['Dashboard']],function(){

    Route::get('dashboard','SuperAdminController@superDashboard');
    //staff
    Route::resource('staff-manage','StaffController');
    Route::post('upload-details','StaffController@uploadstaffdetails');
    Route::get('staff-edit/{id}','StaffController@staffEdit');
    Route::get('approved/{id}','SuperAdminController@approvedByUpper');
    Route::get('staff-active/{id}','SuperAdminController@staffActivation');
    Route::get('staff-block/{id}','SuperAdminController@staffBlock');
    Route::get('staff-detial/{id}','StaffController@staffDetials');
    Route::post('staff-update/{id}','StaffController@staffUpdate');
    Route::get('child-staff/{id}','SuperAdminController@childStaff')->name('superadmin-childstaff');
    Route::get('chek-position/{id}','SuperAdminController@checkPosition');
    Route::get('payment-history','SuperAdminController@paymentHistory');
    Route::get('franchise-tc/{id}','StaffController@franchiseTc');
    //profile
    Route::get('profile-edit', 'ProfileController@edit');
    Route::post('profile-details/{id}', 'ProfileController@update');

app/Models/SubService.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SubService extends Model
{
    public function service()
    {
    	return $this->hasOne('App\Models\Service','id','service_id');
    }

    public function package()
    {
    	return $this->hasOne('App\Models\Packge','sub_service_id','id')->where('is_delete',0);
    }
}

app/Http/Controllers/SubServiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\SubService;
use App\Models\Service;
use Illuminate\Http\Request;

class SubServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $service = Service::get();
        return view('superadmin.sub_service.sub-service-create',compact('service'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' =>  'required',
            'services'  =>  'required',
            'capital'   =>  'required|numeric',
            'profit'    =>  'required|numeric',
            'service_details' => 'required',
            'duration_from' =>  'required|numeric',
            'duration_to' =>  'required|numeric',
            'sample_call'  => 'required', 
            'updates'   => 'required',
            'img'   =>  'required'
        ]);

        $img = $request->file('img');
        $path = public_path().'/assets/home/images/service/';
        $img_name = time().'.'.$img->getClientOriginalExtension();
        $image = $img->move($path,$img_name);

        $sub_service = new SubService;
        $sub_service->service_id = $request->services;
        $sub_service->name = $request->title;
        $sub_service->capital = $request->capital;
        $sub_service->profit = $request->profit;
        $sub_service->duration_from = $request->duration_from;
        $sub_service->duration_to = $request->duration_to;
        $sub_service->service_details = $request->service_details;
        $sub_service->genuine = $request->genuine;
        $sub_service->sample_call = $request->sample_call;
        $sub_service->updates = $request->updates;
        $sub_service->image = $img_name;
        $sub_service->save();

        alert()->success('Service created successfully.');
        return redirect('services-list');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\SubService  $subService
     * @return \Illuminate\Http\Response
     */
    public function show(SubService $subService)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\SubService  $subService
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sub_service = SubService::find($id);
        $service = Service::get();
        return view('superadmin.sub_service.sub_service_edit',compact('sub_service','service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\SubService  $subService
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title' =>  'required',
            'services'  =>  'required',
            'capital'   =>  'required|numeric',
            'profit'    =>  'required|numeric',
            'duration_from' =>  'required|numeric',
            'duration_to' =>  'required|numeric',
            'service_details' => 'required',
            'sample_call'  => 'required', 
            'updates'   => 'required'
        ]);

        $sub_service = SubService::find($id);
        if($request->file('img')){
            try{
                $img = public_path().'/assets/home/images/service/'.$sub_service->image;
                unlink($img);
            }catch(\ErrorException  $e){

            }

            $img = $request->file('img');
            $path = public_path().'/assets/home/images/service/';
            $img_name = time().'.'.$img->getClientOriginalExtension();
            $image = $img->move($path,$img_name);

            $sub_service->image = $img_name;
        }

       

        $sub_service->service_id = $request->services;
        $sub_service->name = $request->title;
        $sub_service->capital = $request->capital;
        $sub_service->profit = $request->profit;
        $sub_service->duration_from = $request->duration_from;
        $sub_service->duration_to = $request->duration_to;
        $sub_service->service_details = $request->service_details;
        $sub_service->sample_call = $request->sample_call;
        $sub_service->updates = $request->updates;
        $sub_service->save();

        alert()->success('Service updated successfully.');
        return redirect('services-list');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\SubService  $subService
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sub_service = SubService::find($id);
        $sub_service->is_delete = 1;
        $sub_service->update();

        alert()->success('Service deleted successfully.');
        return redirect()->back();
    }
}

resources/views/superadmin/sub_service/sub-service-create.blade.php
@extends('layouts.dashboard.master')

@section('title') Sub Service | Dashboard @endsection

@section('style')    
<style type="text/css">
    #sub_service_form label{
    font-size: 18px;
}
</style>
@endsection

@section('content')
<div class="page-body user-management">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6">
                    <h5>Create Sub Service</h5>
                </div>
                <div class="col-lg-6">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>                                
                        <li class="breadcrumb-item active">Sub Service</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="card">
            <div class="edit-form">
                <div class="col-sm-12 ">
                    <div class="card">
                        <div class="card-header b-b-info">
                            <h5>Create Sub Service</h5>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('sub-service.store') }}" method="post" id="sub_service_form" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                <div class="col-md-4 mb-3">
                                    <label>Title</label>
                                    <input type="text" class="form-control" name="title" id="title" placeholder="Title" value="{{ old('title') }}">
                                    @if($errors->has('title'))<strong class="text-danger">{{$errors->first('title')}}</strong>@endif
                                </div>
                                <div class="col-md-4 mb-3">
                                    <label>Services</label>
                                    <select name="services" class="form-control btn-square">
                                        <option name="services" value="">Select Service</option>
                                        @foreach($service as $serv)
                                            <option name="services" value="{{ $serv->id }}">{{ $serv->name }}</option>
                                        @endforeach
                                    </select>
                                     @if($errors->has('services'))<strong class="text-danger">{{$errors->first('services')}}</strong>@endif
                                </div>
                                <div class="col-md-4 mb-3">
                                    <label>Capital Amount </label>
                                    <input type="text" class="form-control" name="capital" id="capital" placeholder="Capital Amount" value="{{ old('capital') }}">
                                     @if($errors->has('capital'))<strong class="text-danger">{{$errors->first('capital')}}</strong>@endif
                                </div>
                                <div class="col-md-4 mb-3">
                                    <label>Profit Amount</label>
                                    <input type="text" class="form-control" name="profit" id="profit" placeholder="Profit Amount" value="{{ old('profit') }}">
                                     @if($errors->has('profit'))<strong class="text-danger">{{$errors->first('profit')}}</strong>@endif
                                </div>
                                <div class="col-md-10 mb-3">
                                    <label>Duration</label>
                                    <div class="row  m-b-15">
                                        <div class="col-sm-3 pl-4">
                                        <input type="text" class="form-control" name="duration_from" id="duration_from" placeholder="Form" value="{{ old('duration_from') }}"> 
                                         @if($errors->has('duration_from'))<strong class="text-danger">{{$errors->first('duration_from')}}<br></strong>@endif 
                                         </div>
                                        <div class="col-sm-3 pl-4"> 
                                        <input type="text" class="form-control" name="duration_to" id="duration_to" placeholder="To" value="{{ old('duration_to') }}"><label class="form-label"></label>
                                         @if($errors->has('duration_to'))<strong class="text-danger">{{$errors->first('duration_to')}}</strong>@endif
                                         </div>
                                         <div class="col-sm-2">
                                            <label>Days</label>
                                         </div>
                                     </div>
                                 </div>
                                <div class="form-group">
                                    <label>Service Details</label>
                                    <textarea name="service_details" class="form-control" id="editor1" cols="20" rows="15" value="{{ old('service_details') }}">{{ old('service_details') }}</textarea>
                                     @if($errors->has('service_details'))<strong class="text-danger">{{$errors->first('service_details')}}</strong>@endif
                                </div>
                               
                                <div class="form-group">
                                    <label>Sample Call</label>
                                    <textarea name="sample_call" class="form-control" id="editor3" cols="20" rows="15" value="{{ old('sample_call') }}">{{ old('sample_call') }}</textarea>
                                     @if($errors->has('sample_call'))<strong class="text-danger">{{$errors->first('sample_call')}}</strong>@endif
                                </div>
                                <div class="form-group">
                                    <label>Updates</label>
                                    <textarea name="updates" class="form-control" id="editor4" cols="20" rows="15" value="{{ old('updates') }}">{{ old('updates') }}</textarea>
                                    @if($errors->has('updates'))<strong class="text-danger">{{$errors->first('updates')}}</strong>@endif
                                </div>
                                <div class="form-group">
                                    <input type="file" name="img" value="{{ old('img') }}">
                                    @if($errors->has('img'))<strong class="text-danger">{{$errors->first('img')}}</strong>@endif
                                </div>
                                <button class="btn btn-primary" type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

@section('script')


@endsection

resources/views/superadmin/sub_service/sub_service_edit.blade.php
@extends('layouts.dashboard.master')

@section('title') {{ $sub_service->name }} | Service @endsection

@section('style')    

@endsection

@section('content')
<div class="page-body user-management">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-lg-6">
                    <h5>Edit {{ $sub_service->name }}</h5>
                </div>
                <div class="col-lg-6">
                    <ol class="breadcrumb pull-right">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
                        <li class="breadcrumb-item">Service</li>                                  
                        <li class="breadcrumb-item active">{{ $sub_service->name }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="card">
            <div class="edit-form">
                <div class="card-header b-b-info">
                    <h4>{{ $sub_service->name }}</h4>
                </div>
                <div class="card-body">
                    <form action="{{ route('sub-service.update',$sub_service->id) }}" method="post" id="sub_service_form" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="col-md-4 mb-3">
                            <label>Title</label>
                            <input type="text" class="form-control" name="title" id="title" placeholder="Title" value="{{ $sub_service->name }}">
                            @if($errors->has('title'))<strong class="text-danger">{{$errors->first('title')}}</strong>@endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label>Services</label>
                            <select name="services" class="form-control btn-square">
                                <option name="services" value="">Select Service</option>
                                @foreach($service as $serv)
                                    <option name="services" value="{{ $serv->id }}" {{ $serv->id == $sub_service->service_id ? 'selected':'' }}>{{ $serv->name }}</option>
                                @endforeach
                            </select>
                             @if($errors->has('services'))<strong class="text-danger">{{$errors->first('services')}}</strong>@endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label>Capital Amount </label>
                            <input type="text" class="form-control" name="capital" id="capital" placeholder="Capital Amount" value="{{ $sub_service->capital }}">
                             @if($errors->has('capital'))<strong class="text-danger">{{$errors->first('capital')}}</strong>@endif
                        </div>
                        <div class="col-md-4 mb-3">
                            <label>Profit Amount</label>
                            <input type="text" class="form-control" name="profit" id="profit" placeholder="Profit Amount" value="{{ $sub_service->profit }}">
                             @if($errors->has('profit'))<strong class="text-danger">{{$errors->first('profit')}}</strong>@endif
                        </div>
                        <div class="col-md-10 mb-3">
                            <label>Duration</label>
                            <div class="row  m-b-15">
                                <div class="col-sm-3 pl-4">
                                <input type="text" class="form-control" name="duration_from" id="duration_from" placeholder="Form" value="{{ $sub_service->duration_from }}"> 
                                 @if($errors->has('duration_from'))<strong class="text-danger">{{$errors->first('duration_from')}}<br></strong>@endif 
                                 </div>
                                <div class="col-sm-3 pl-4"> 
                                <input type="text" class="form-control" name="duration_to" id="duration_to" placeholder="To" value="{{ $sub_service->duration_to }}"><label class="form-label"></label>
                                 @if($errors->has('duration_to'))<strong class="text-danger">{{$errors->first('duration_to')}}</strong>@endif
                                 </div>
                                 <div class="col-sm-2">
                                    <label>Days</label>
                                 </div>
                             </div>
                         </div>
                        <div class="form-group">
                            <label>Service Details</label>
                            <textarea name="service_details" class="form-control" id="editor1" cols="20" rows="15" value="{{ $sub_service->service_details }}">{{ $sub_service->service_details }}</textarea>
                             @if($errors->has('service_details'))<strong class="text-danger">{{$errors->first('service_details')}}</strong>@endif
                        </div>
                        <div class="form-group">
                            <label>Sample Call</label>
                            <textarea name="sample_call" class="form-control" id="editor3" cols="20" rows="15" value="{{ $sub_service->sample_call }}">{{ $sub_service->sample_call }}</textarea>
                             @if($errors->has('sample_call'))<strong class="text-danger">{{$errors->first('sample_call')}}</strong>@endif
                        </div>
                        <div class="form-group">
                            <label>Updates</label>
                            <textarea name="updates" class="form-control" id="editor4" cols="20" rows="15" value="{{ $sub_service->updates }}">{{ $sub_service->updates }}</textarea>
                            @if($errors->has('updates'))<strong class="text-danger">{{$errors->first('updates')}}</strong>@endif
                        </div>
                        <div class="form-group">
                            <input type="file" name="img" value="{{ old('img') }}">
                        </div>
                            @if($errors->has('img'))<strong class="text-danger">{{$errors->first('img')}}</strong>@endif
                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

@section('script')


@endsection